#![feature(abi_msp430_interrupt)]
#![doc = "Peripheral access API for MSP430FR2355 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[allow(unused_imports)]
use generic::*;
#[cfg(feature = "rt")]
pub use msp430_rt::interrupt;
#[doc = "Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "msp430-interrupt" {
    fn PORT4();
    fn PORT3();
    fn PORT2();
    fn PORT1();
    fn SAC1_SAC3();
    fn SAC0_SAC2();
    fn ECOMP0_ECOMP1();
    fn ADC();
    fn EUSCI_B1();
    fn EUSCI_B0();
    fn EUSCI_A1();
    fn EUSCI_A0();
    fn WDT();
    fn RTC();
    fn TIMER3_B1();
    fn TIMER3_B0();
    fn TIMER2_B1();
    fn TIMER2_B0();
    fn TIMER1_B1();
    fn TIMER1_B0();
    fn TIMER0_B1();
    fn TIMER0_B0();
    fn UNMI();
    fn SYSNMI();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "msp430-interrupt" fn(),
    _reserved: u16,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
#[used]
pub static __INTERRUPTS: [Vector; 45] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PORT4 },
    Vector { _handler: PORT3 },
    Vector { _handler: PORT2 },
    Vector { _handler: PORT1 },
    Vector {
        _handler: SAC1_SAC3,
    },
    Vector {
        _handler: SAC0_SAC2,
    },
    Vector {
        _handler: ECOMP0_ECOMP1,
    },
    Vector { _handler: ADC },
    Vector { _handler: EUSCI_B1 },
    Vector { _handler: EUSCI_B0 },
    Vector { _handler: EUSCI_A1 },
    Vector { _handler: EUSCI_A0 },
    Vector { _handler: WDT },
    Vector { _handler: RTC },
    Vector {
        _handler: TIMER3_B1,
    },
    Vector {
        _handler: TIMER3_B0,
    },
    Vector {
        _handler: TIMER2_B1,
    },
    Vector {
        _handler: TIMER2_B0,
    },
    Vector {
        _handler: TIMER1_B1,
    },
    Vector {
        _handler: TIMER1_B0,
    },
    Vector {
        _handler: TIMER0_B1,
    },
    Vector {
        _handler: TIMER0_B0,
    },
    Vector { _handler: UNMI },
    Vector { _handler: SYSNMI },
];
#[doc = r"Enumeration of all the interrupts. This enum is seldom used in application or library crates. It is present primarily for documenting the device's implemented interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "21 - 0xFFCE"]
    PORT4 = 21,
    #[doc = "22 - 0xFFD0"]
    PORT3 = 22,
    #[doc = "23 - 0xFFD2"]
    PORT2 = 23,
    #[doc = "24 - 0xFFD4"]
    PORT1 = 24,
    #[doc = "25 - 0xFFD6"]
    SAC1_SAC3 = 25,
    #[doc = "26 - 0xFFD8"]
    SAC0_SAC2 = 26,
    #[doc = "27 - 0xFFDA"]
    ECOMP0_ECOMP1 = 27,
    #[doc = "28 - 0xFFDC"]
    ADC = 28,
    #[doc = "29 - 0xFFDE"]
    EUSCI_B1 = 29,
    #[doc = "30 - 0xFFE0"]
    EUSCI_B0 = 30,
    #[doc = "31 - 0xFFE2"]
    EUSCI_A1 = 31,
    #[doc = "32 - 0xFFE4"]
    EUSCI_A0 = 32,
    #[doc = "33 - 0xFFE6"]
    WDT = 33,
    #[doc = "34 - 0xFFE8"]
    RTC = 34,
    #[doc = "35 - 0xFFEA"]
    TIMER3_B1 = 35,
    #[doc = "36 - 0xFFEC"]
    TIMER3_B0 = 36,
    #[doc = "37 - 0xFFEE"]
    TIMER2_B1 = 37,
    #[doc = "38 - 0xFFF0"]
    TIMER2_B0 = 38,
    #[doc = "39 - 0xFFF2"]
    TIMER1_B1 = 39,
    #[doc = "40 - 0xFFF4"]
    TIMER1_B0 = 40,
    #[doc = "41 - 0xFFF6"]
    TIMER0_B1 = 41,
    #[doc = "42 - 0xFFF8"]
    TIMER0_B0 = 42,
    #[doc = "43 - 0xFFFA"]
    UNMI = 43,
    #[doc = "44 - 0xFFFC"]
    SYSNMI = 44,
}
#[doc = "P1"]
pub type P1 = crate::Periph<p1::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1").finish()
    }
}
#[doc = "P1"]
pub mod p1;
#[doc = "P2"]
pub type P2 = crate::Periph<p2::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P2").finish()
    }
}
#[doc = "P2"]
pub mod p2;
#[doc = "P3"]
pub type P3 = crate::Periph<p3::RegisterBlock, 0x0220>;
impl core::fmt::Debug for P3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P3").finish()
    }
}
#[doc = "P3"]
pub mod p3;
#[doc = "P4"]
pub type P4 = crate::Periph<p4::RegisterBlock, 0x0220>;
impl core::fmt::Debug for P4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P4").finish()
    }
}
#[doc = "P4"]
pub mod p4;
#[doc = "P5"]
pub type P5 = crate::Periph<p5::RegisterBlock, 0x0240>;
impl core::fmt::Debug for P5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P5").finish()
    }
}
#[doc = "P5"]
pub mod p5;
#[doc = "P6"]
pub type P6 = crate::Periph<p6::RegisterBlock, 0x0240>;
impl core::fmt::Debug for P6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P6").finish()
    }
}
#[doc = "P6"]
pub mod p6;
#[doc = "SFR"]
pub type Sfr = crate::Periph<sfr::RegisterBlock, 0x0100>;
impl core::fmt::Debug for Sfr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sfr").finish()
    }
}
#[doc = "SFR"]
pub mod sfr;
#[doc = "PMM"]
pub type Pmm = crate::Periph<pmm::RegisterBlock, 0x0120>;
impl core::fmt::Debug for Pmm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmm").finish()
    }
}
#[doc = "PMM"]
pub mod pmm;
#[doc = "SYS"]
pub type Sys = crate::Periph<sys::RegisterBlock, 0x0140>;
impl core::fmt::Debug for Sys {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sys").finish()
    }
}
#[doc = "SYS"]
pub mod sys;
#[doc = "CS"]
pub type Cs = crate::Periph<cs::RegisterBlock, 0x0180>;
impl core::fmt::Debug for Cs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cs").finish()
    }
}
#[doc = "CS"]
pub mod cs;
#[doc = "FRCTL"]
pub type Frctl = crate::Periph<frctl::RegisterBlock, 0x01a0>;
impl core::fmt::Debug for Frctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Frctl").finish()
    }
}
#[doc = "FRCTL"]
pub mod frctl;
#[doc = "CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x01c0>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC"]
pub mod crc;
#[doc = "WDT_A"]
pub type WdtA = crate::Periph<wdt_a::RegisterBlock, 0x01cc>;
impl core::fmt::Debug for WdtA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtA").finish()
    }
}
#[doc = "WDT_A"]
pub mod wdt_a;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x0300>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "TB0"]
pub type Tb0 = crate::Periph<tb0::RegisterBlock, 0x0380>;
impl core::fmt::Debug for Tb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tb0").finish()
    }
}
#[doc = "TB0"]
pub mod tb0;
#[doc = "TB1"]
pub type Tb1 = crate::Periph<tb1::RegisterBlock, 0x03c0>;
impl core::fmt::Debug for Tb1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tb1").finish()
    }
}
#[doc = "TB1"]
pub mod tb1;
#[doc = "TB2"]
pub type Tb2 = crate::Periph<tb2::RegisterBlock, 0x0400>;
impl core::fmt::Debug for Tb2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tb2").finish()
    }
}
#[doc = "TB2"]
pub mod tb2;
#[doc = "TB3"]
pub type Tb3 = crate::Periph<tb3::RegisterBlock, 0x0440>;
impl core::fmt::Debug for Tb3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tb3").finish()
    }
}
#[doc = "TB3"]
pub mod tb3;
#[doc = "MPY32"]
pub type Mpy32 = crate::Periph<mpy32::RegisterBlock, 0x04c0>;
impl core::fmt::Debug for Mpy32 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mpy32").finish()
    }
}
#[doc = "MPY32"]
pub mod mpy32;
#[doc = "eUSCI_A0"]
pub type EUsciA0 = crate::Periph<e_usci_a0::RegisterBlock, 0x0500>;
impl core::fmt::Debug for EUsciA0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA0").finish()
    }
}
#[doc = "eUSCI_A0"]
pub mod e_usci_a0;
#[doc = "eUSCI_B0"]
pub type EUsciB0 = crate::Periph<e_usci_b0::RegisterBlock, 0x0540>;
impl core::fmt::Debug for EUsciB0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciB0").finish()
    }
}
#[doc = "eUSCI_B0"]
pub mod e_usci_b0;
#[doc = "eUSCI_A1"]
pub type EUsciA1 = crate::Periph<e_usci_a1::RegisterBlock, 0x0580>;
impl core::fmt::Debug for EUsciA1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA1").finish()
    }
}
#[doc = "eUSCI_A1"]
pub mod e_usci_a1;
#[doc = "eUSCI_B1"]
pub type EUsciB1 = crate::Periph<e_usci_b1::RegisterBlock, 0x05c0>;
impl core::fmt::Debug for EUsciB1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciB1").finish()
    }
}
#[doc = "eUSCI_B1"]
pub mod e_usci_b1;
#[doc = "BAKMEM"]
pub type Bakmem = crate::Periph<bakmem::RegisterBlock, 0x0660>;
impl core::fmt::Debug for Bakmem {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bakmem").finish()
    }
}
#[doc = "BAKMEM"]
pub mod bakmem;
#[doc = "ICC"]
pub type Icc = crate::Periph<icc::RegisterBlock, 0x06c0>;
impl core::fmt::Debug for Icc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icc").finish()
    }
}
#[doc = "ICC"]
pub mod icc;
#[doc = "ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x0700>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "ADC"]
pub mod adc;
#[doc = "eCOMP0"]
pub type EComp0 = crate::Periph<e_comp0::RegisterBlock, 0x08e0>;
impl core::fmt::Debug for EComp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EComp0").finish()
    }
}
#[doc = "eCOMP0"]
pub mod e_comp0;
#[doc = "eCOMP1"]
pub type EComp1 = crate::Periph<e_comp1::RegisterBlock, 0x0900>;
impl core::fmt::Debug for EComp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EComp1").finish()
    }
}
#[doc = "eCOMP1"]
pub mod e_comp1;
#[doc = "SAC0"]
pub type Sac0 = crate::Periph<sac0::RegisterBlock, 0x0c80>;
impl core::fmt::Debug for Sac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sac0").finish()
    }
}
#[doc = "SAC0"]
pub mod sac0;
#[doc = "SAC1"]
pub type Sac1 = crate::Periph<sac1::RegisterBlock, 0x0c90>;
impl core::fmt::Debug for Sac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sac1").finish()
    }
}
#[doc = "SAC1"]
pub mod sac1;
#[doc = "SAC2"]
pub type Sac2 = crate::Periph<sac2::RegisterBlock, 0x0ca0>;
impl core::fmt::Debug for Sac2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sac2").finish()
    }
}
#[doc = "SAC2"]
pub mod sac2;
#[doc = "SAC3"]
pub type Sac3 = crate::Periph<sac3::RegisterBlock, 0x0cb0>;
impl core::fmt::Debug for Sac3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sac3").finish()
    }
}
#[doc = "SAC3"]
pub mod sac3;
#[doc = "Device descriptors (TLV)"]
pub type Tlv = crate::Periph<tlv::RegisterBlock, 0x1a00>;
impl core::fmt::Debug for Tlv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tlv").finish()
    }
}
#[doc = "Device descriptors (TLV)"]
pub mod tlv;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "P1"]
    pub p1: P1,
    #[doc = "P2"]
    pub p2: P2,
    #[doc = "P3"]
    pub p3: P3,
    #[doc = "P4"]
    pub p4: P4,
    #[doc = "P5"]
    pub p5: P5,
    #[doc = "P6"]
    pub p6: P6,
    #[doc = "SFR"]
    pub sfr: Sfr,
    #[doc = "PMM"]
    pub pmm: Pmm,
    #[doc = "SYS"]
    pub sys: Sys,
    #[doc = "CS"]
    pub cs: Cs,
    #[doc = "FRCTL"]
    pub frctl: Frctl,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "WDT_A"]
    pub wdt_a: WdtA,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "TB0"]
    pub tb0: Tb0,
    #[doc = "TB1"]
    pub tb1: Tb1,
    #[doc = "TB2"]
    pub tb2: Tb2,
    #[doc = "TB3"]
    pub tb3: Tb3,
    #[doc = "MPY32"]
    pub mpy32: Mpy32,
    #[doc = "E_USCI_A0"]
    pub e_usci_a0: EUsciA0,
    #[doc = "E_USCI_B0"]
    pub e_usci_b0: EUsciB0,
    #[doc = "E_USCI_A1"]
    pub e_usci_a1: EUsciA1,
    #[doc = "E_USCI_B1"]
    pub e_usci_b1: EUsciB1,
    #[doc = "BAKMEM"]
    pub bakmem: Bakmem,
    #[doc = "ICC"]
    pub icc: Icc,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "E_COMP0"]
    pub e_comp0: EComp0,
    #[doc = "E_COMP1"]
    pub e_comp1: EComp1,
    #[doc = "SAC0"]
    pub sac0: Sac0,
    #[doc = "SAC1"]
    pub sac1: Sac1,
    #[doc = "SAC2"]
    pub sac2: Sac2,
    #[doc = "SAC3"]
    pub sac3: Sac3,
    #[doc = "TLV"]
    pub tlv: Tlv,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            p1: P1::steal(),
            p2: P2::steal(),
            p3: P3::steal(),
            p4: P4::steal(),
            p5: P5::steal(),
            p6: P6::steal(),
            sfr: Sfr::steal(),
            pmm: Pmm::steal(),
            sys: Sys::steal(),
            cs: Cs::steal(),
            frctl: Frctl::steal(),
            crc: Crc::steal(),
            wdt_a: WdtA::steal(),
            rtc: Rtc::steal(),
            tb0: Tb0::steal(),
            tb1: Tb1::steal(),
            tb2: Tb2::steal(),
            tb3: Tb3::steal(),
            mpy32: Mpy32::steal(),
            e_usci_a0: EUsciA0::steal(),
            e_usci_b0: EUsciB0::steal(),
            e_usci_a1: EUsciA1::steal(),
            e_usci_b1: EUsciB1::steal(),
            bakmem: Bakmem::steal(),
            icc: Icc::steal(),
            adc: Adc::steal(),
            e_comp0: EComp0::steal(),
            e_comp1: EComp1::steal(),
            sac0: Sac0::steal(),
            sac1: Sac1::steal(),
            sac2: Sac2::steal(),
            sac3: Sac3::steal(),
            tlv: Tlv::steal(),
        }
    }
}
